name: Run collector.py file

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/120 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install telethon
        pip install pytz
        pip install jdatetime

    - name: Run Python script
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
      run: |
        python Scripts/Collector.py

      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update files" || exit 0  # Exit successfully if there's nothing to commit
        git push --force
